[package]
name = "v1-0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
concrete="^0.1"
indicatif = "0.16.2"
TFHE_concurrency = { git = "https://github.com/henrikfo/TFHE_concurrency" }