[package]
name = "ewma_GVI"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
concrete = "0.1.9"
ndarray = "*"
ndarray-csv = "*"
csv = "*"